version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - .db_data:/app/db_data
    expose:
      - 8000
    networks:
      [ wikisoup ]

  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: docker/webserver/Dockerfile
    expose:
      - 80
    networks:
      [ wikisoup ]
    depends_on:
      - backend

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./frontend:/var/www/matrix.com/static
    ports:
      - "80:80"
    networks:
      [ wikisoup ]
    depends_on:
      - backend
      - webserver

networks:
  wikisoup:
    name: wikisoup